### ISSUE TITLE
(BUG) Two `_links` are sent from the API

### ISSUE THREAD

**Issue by dusan-turajlic** [TurkuForge/baby-project-server#14]
## Detailed Description

When you fire a request agesnt [api](https://api.turkuforge.fi/) it returns a response that looks like this
```json
{
  "_embedded": {
    "bp:channelList": [
      {
        "name": "general",
        "subscription": "/channel/general",
        "_links": {
          "self": {
            "href": "https://api.turkuforge.fi/channel/general"
          }
        }
      },
      {
        "name": "random",
        "subscription": "/channel/random",
        "_links": {
          "self": {
            "href": "https://api.turkuforge.fi/channel/random"
          }
        }
      }
    ]
  },
  "_links": {
    "curies": [
      {
        "href": "https://docs.turkuforge.fi/{#rel}",
        "name": "bp",
        "templated": true
      }
    ]
  },
  "_links": {
    "bp:sockjs-endpoint": {
      "href": "https://api.turkuforge.fi/connect"
    },
    "self": {
      "href": "https://api.turkuforge.fi"
    },
    "curies": [
      {
        "href": "https://docs.turkuforge.fi/{#rel}",
        "name": "bp",
        "templated": true
      }
    ]
  }
}
```
**NOTE The two `_links`!**
That should not be there!

## Context

This is a problem when different client have different types of JSON parsers and they treat these senarios differently since its agenst the JSON specification. On the iOS client it prioritized the first linka and ignores the second one compleatly, that is a problem since we pass relevent links like how to connect to the websocket endpoint.

## Expected Behavior

It should only have one link with `bp:sockjs-endpoint`, `self` and `curies`

## Actual Behavior

It has two links one with only `curies` and one with everything else.

## Steps to Reproduce

```shell
curl -i https://api.turkuforge.fi/
```

## Possible Fix

🤷🏻‍♂️

**Comment by edrik** [comment]
Don't think you should add links to the `RepresentationModel` one you have called `build()` on the `HalModelBuilder`. The builder has `link()` methods specifically for adding links to the top level.

**Comment by dusan-turajlic** [comment]
@edrik I agree that that is a good improvment but it does not fix my problem. The problem seems to be with the HALModel builder not really having support for curies in embedded resources. If I specify a relatuon manualy for embedded it solves the problem, but if I add any kind of curie it will add the second `_link` to the response. I added a Issue with spring HEATOES for this. I havent really had time ti dig in to the issue my self yet but I will add a PR to Spring HEATOES once I have a solution.

**Comment by dusan-turajlic** [comment]
We created a tempraray workaround for the issue and have a open PR that will remove that workaround once Spring HATEOAS creates a July release
